name: lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.1

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.4
        with:
          cache: npm
          cache-dependency-path: tree-sitter-topas/package-lock.json
          
      - name: Install modules
        run: npm ci
        working-directory: tree-sitter-topas/
        
      - name: Run ESLint
        run: npx eslint grammar.js
        working-directory: tree-sitter-topas/
