name: Publish release

on: 
  push:
    branches: 
      - main
    tags: ["*"]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    uses: tree-sitter/workflows/.github/workflows/release.yml@main
    with:
      generate: true
